version: '3.8'

services:
  api:
    build: .
    container_name: api_localidade
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
      - RATE_LIMIT=${RATE_LIMIT:-10/hour}
    env_file:
      - .env
    restart: unless-stopped
